home:
    path: /
    controller: App\Controller\DefaultController::indexAction

about:
    path: /about
    controller: App\Controller\DefaultController::aboutAction

admin:
    path: /admin
    controller: App\Controller\AdminController::adminAction
    

skills:
    path : /admin/skill
    controller: App\Controller\AdminController::skillAction

skill_update:
    path: admin/skill_update
    controller: App\Controller\AdminController::skillUpdateAction
