home:
    path: /
    controller: App\Controller\DefaultController::indexAction

about:
    path: /about
    controller: App\Controller\DefaultController::aboutAction

admin:
    path: /admin
    controller: App\Controller\AdminController::adminAction
    

skills:
    path : /admin/skill
    controller: App\Controller\AdminController::skillAction

skill_add:
    path: /admin/skill/add
    controller: App\Controller\AdminController::skillAddAction

skill_update:
    path: /admin/skill/{id}/update
    controller: App\Controller\AdminController::skillUpdateAction

projects:
    path: /admin/project
    controller: App\Controller\AdminController::projectAction

project_update:
    path: /admin/project/{id}/update
    controller: App\Controller\AdminController::projectUpdateAction


