home:
    path: /
    controller: App\Controller\DefaultController::indexAction

about:
    path: /about
    controller: App\Controller\DefaultController::aboutAction

admin:
    path: /admin
    controller: App\Controller\AdminController::adminAction
    

skills:
    path : /admin/skills
    controller: App\Controller\AdminController::skillAction

skill_add:
    path: /admin/skill/add
    controller: App\Controller\AdminController::skillAddAction

skill_update:
    path: /admin/skill/{id}/update
    controller: App\Controller\AdminController::skillUpdateAction

skill_delete:
    path: /admin/skill/{id}/delete
    controller: App\Controller\AdminController::skillDeleteAction

projects:
    path: /admin/projects
    controller: App\Controller\AdminController::projectAction

project_add:
    path: /admin/project/add
    controller: App\Controller\AdminController::projectAddAction

project_update:
    path: /admin/project/{id}/update
    controller: App\Controller\AdminController::projectUpdateAction

project_delete:
    path: /admin/project/{id}/delete
    controller: App\Controller\AdminController::projectDeleteAction

technos:
    path: /admin/technos
    controller: App\Controller\AdminController::technoAction

techno_add:
    path: /admin/techno/add
    controller: App\Controller\AdminController::technoAddAction

techno_update:
    path: /admin/techno/{id}/update
    controller: App\Controller\AdminController::technoUpdateAction

techno_delete:
    path: /admin/techno/{id}/delete
    controller: App\Controller\AdminController::technoDeleteAction

categories:
    path: /admin/categories
    controller: App\Controller\AdminController::categoryAction

category_add:
    path: /admin/category/add
    controller: App\Controller\AdminController::categoryAddAction

category_update:
    path: /admin/category/{id}/update
    controller: App\Controller\AdminController::categoryUpdateAction

category_delete:
    path: /admin/category/{id}/delete
    controller: App\Controller\AdminController::categoryDeleteAction
